@startuml


  node "Raspberry Pi" {
    database Raum_DB
    component "Raumserver"
    component "Temperatursensor"
  }
  node "Heizungsventil"




cloud Heroku {
  database Backend_DB
  node Tomcat {
    component "Backend"
  }
}

node Smartphone {
  component App
}

App -- Backend
Raumserver -- Raum_DB
Raumserver -- Heizungsventil
Raumserver -- Temperatursensor
Raumserver -- Backend
Backend -- Backend_DB


@enduml
