@startuml


  node "Raspberry Pi" <<device>> {
    [Room Server]
    database "Room Server DB" {
      [Room Data] - [Room Server]
    }
  }

  node "Temperature_Sensor" <<device>> #white
  node "Heating Valve" <<device>> {
    [Valve Controller] - [Room Server]
  }




cloud Heroku <<platform service>>{

    [Cloud Backend]
    [Cloud Backend] - [Room Server]

database "Backend DB"{

  [User Data] - [Cloud Backend]
}

}

node Smartphone <<device>> {
  node "Device OS" <<platform>> {
    [Home Automation Client] - [Cloud Backend] 
  }
}

Temperature_Sensor - [Room Server]


@enduml
