@startuml
left to right direction
skinparam packageStyle rect
actor tenant
node Heating_Valve <<device>> {

}
node Temperature_Sensor <<device>> {

}
rectangle "Home Automation" {
  tenant - (observe temerature)

  Temperature_Sensor - (measure temperature)
  (controle heating) - Heating_Valve 

  (observe temerature) .> (tenant authentication) : include
  (set temerature) .> (tenant authentication) : include
  tenant - (set temerature)
}


@enduml
